app:
  title: Scaffolded Backstage App
  baseUrl: http://localhost:3000

  packages: all

  extensions:
    - page:catalog:
        config:
          path: /

organization:
  name: My Company

backend:
  baseUrl: https://turbo-enigma-6qqx65v59pj24xxw-7007.app.github.dev
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin:
      - http://localhost:3000
      - https://turbo-enigma-6qqx65v59pj24xxw-3000.app.github.dev
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'

auth:
  providers:
    guest: {}

scaffolder:
  defaultAuthor:
    name: IDP
    email: idp@example.com

catalog:
  locations:
    - type: file
      target: /workspaces/idp-self-service-platform/backstage-app/packages/backend/catalog-info.yaml
      rules:
        - allow: [Location, Template]